baseurl = "https://kplat.is"
title = "kplat.is"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Konstantinos Platis"
  info = "Full Stack Developer"
  description = "Konstantinos Platis' personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/images/me.jpg"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/kplatis"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/kplat_is"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/konstantinosplatis/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url  = "about"
[[menu.main]]
  name = "Experience"
  weight = 2
  url = "experience/"
[[menu.main]]
  name = "Education"
  weight = 3
  url = "education/"